params:
  algo:
    name: a2c_continuous
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 2
    device: cuda:1
    device_name: cuda:1
    e_clip: 0.2
    entropy_coef: 0.0
    env_name: rlgpu
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 48
    kl_threshold: 0.016
    learning_rate: 5e-4
    lr_schedule: adaptive
    max_epochs: 300
    mini_epochs: 5
    minibatch_size: 24576
    multi_gpu: false
    name: kingfisher_direct_low_level_ll_model_011
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    num_actors: -1
    ppo: true
    reward_shaper:
      scale_value: 0.01
    save_best_after: 25
    save_frequency: 50
    schedule_type: legacy
    score_to_win: 20000000
    seq_length: 4
    tau: 0.95
    truncate_grads: true
    value_bootstrap: true
  env:
    clip_actions: 1.0
  load_checkpoint: false
  load_path: ''
  model:
    name: continuous_a2c_logstd
  network:
    mlp:
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 64
      - 64
    name: actor_critic
    separate: false
    space:
      continuous:
        fixed_sigma: true
        mu_activation: None
        mu_init:
          name: default
        sigma_activation: None
        sigma_init:
          name: const_initializer
          val: 0
  seed: 1
