# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import torch
from dataclasses import MISSING
import math
from dataclasses import field
from omni.isaac.lab.utils import configclass
from omni.isaac.lab.utils.math import quat_rotate_inverse
import matplotlib.pyplot as plt
from xfoil import XFoil
from xfoil.model import Airfoil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import interpolate
from omni.isaac.lab.utils.interpolation import LinearInterpolation

import pandas as pd

# File path to the Naca profile downloaded from xfoil
filepath = "/home/isaac_user/asv-sawasp-fousseyni/Usd/naca0018.csv"
df = pd.read_csv(filepath, skiprows=8, nrows=201)
#print(df.head)

x_coords_naca = 1e-2*df[["X(mm)"]].values
y_coords_naca = 1e-2*df[["Y(mm)"]].values

@configclass
class AerodynamicsCfg:
    """Configuration for hydrodynamics."""

    wind_direction:float = MISSING # rad/s
    wind_speed:float = MISSING # m/s
    min_upwind_angle:float = MISSING # m/s # Minimum upwind tolerable angle
    max_downwind_angle:float = MISSING # m/s # Maximum downwind tolerable angle

    angle_of_attack: float = MISSING # angle of attack of the sail w.r.t wind

    wing_span:float = MISSING # span/length of the sail wing in meter
    wing_chord:float = MISSING # chord/width of the sail wing in meter

    air_density :float = MISSING # air density


class Aerodynamics:
    def __init__(self, num_envs, device, cfg: AerodynamicsCfg):

        self.num_envs = num_envs
        self.device = device
        self.cfg = cfg

        self.angle_of_attack = self.cfg.angle_of_attack*torch.ones(self.num_envs, device=self.device)
        self.sail_angle = torch.zeros(self.num_envs, device=self.device)
        self.apparent_wind_angle = torch.zeros(self.num_envs, device=self.device)
        self.apparent_wind_speed_b = torch.zeros((self.num_envs, 2), device=self.device)
        self.true_wind_speed2D_b = torch.zeros((self.num_envs, 2), device=self.device)
        
        self.Uw = self.cfg.wind_speed*torch.ones(self.num_envs, device=self.device) # wind speed of 10 meters per second
        self.Beta_w = self.cfg.wind_direction*torch.ones(self.num_envs, device=self.device) # wind angle of 80 degrees = 80*pi/180 radian
        self.wind_force = torch.zeros((self.num_envs, 3), device=self.device)

        self.lift_coeff = torch.zeros_like(self.Beta_w)
        self.drag_coeff = torch.zeros_like(self.Beta_w)
        
        # lift and drag in the boat frame
        self.wind_lift_b = torch.zeros((self.num_envs, 3), device=self.device) 
        self.wind_drag_b = torch.zeros((self.num_envs, 3), device=self.device)

        # lift and drag in the wing frame
        self.wind_lift_wing = torch.zeros((self.num_envs, 3), device=self.device) 
        self.wind_drag_wing = torch.zeros((self.num_envs, 3), device=self.device)

        self.xfoil = XFoil()
        self.xfoil.print = False
        self.airfoil_set = False
        self.xfoil.airfoil = Airfoil(x_coords_naca, y_coords_naca)  # set later
        
        self.xfoil.n_crit = 9
        self.max_cl_cd_ratio = 0
        self.max_cl = 0
        #self._aerodynamics.xfoil = self.xfoil

        self.sail_unit_vector = torch.zeros_like(self.apparent_wind_speed_b)
        self.sail_ortho_unit_vector = torch.zeros_like(self.apparent_wind_speed_b)

        #self.xfoil = None

        # These coefficients interpolators are initialised in the environement
        self.lift_coeff_interpolator = None
        self.drag_coeff_interpolator = None

        self.set_coeffs_interpolators()

        """vectors = {
                    "apparent_wind_speed": torch.zeros((self.num_envs, 2), device=self.device), 
                    "true_wind_speed":torch.zeros((self.num_envs, 2), device=self.device),
                    "lift":torch.zeros((self.num_envs, 3), device=self.device) ,
                    "drag":torch.zeros((self.num_envs, 3), device=self.device)
                    }
        
        self.frames = {"world": vectors, "boat":vectors, "wing":vectors}"""

        return
    
    def compute_wind_effect(self, Uw:torch.Tensor, Beta_w:torch.Tensor, ship_heading_w:torch.Tensor,
                                 ship_lin_vel2D)->torch.Tensor:
        """ This function will be used to apply wind effect:
                Parameters:
            - Uw: (true) wind speed for all environmenents
            - Beta_w: (true) wind direction for all environmenents
            - ship_heading: heading of the ship in global frame
            - ship_lin_vel2D: 2D coordinates of the linear velocity of the ship in the local (ship) frame
            - AspectR: aspect ratio of the wing -> span/chord

                Return:
            - Lift and Drag tensors generated by the wind in all environment
        """

        sail_wing_aire = self.cfg.wing_span*self.cfg.wing_chord
        density_p = self.cfg.air_density

        # True wind in sailboat frame
        self.true_wind_speed2D_b = self.generate_true_wind_components(Uw, Beta_w, ship_heading_w) # ok

        apparent_wind2D_b = self.generate_apparent_wind_components(self.true_wind_speed2D_b, ship_lin_vel2D)

        self.apparent_wind_speed_b = apparent_wind2D_b.clone()
        self.apparent_wind_angle = self.get_apparent_wind_angle(apparent_wind2D_b)
        AspectR = self.cfg.wing_span/self.cfg.wing_chord # Aspect ratio of the rigid wing

        Re = self.compute_Reynold(Uw, self.cfg.wing_chord)
        t = 0.18*self.cfg.wing_chord # thickness, naca0018 so 18% of the chord
        coeff_L, coeff_D = self.generate_coeffs((180/torch.pi)*self.angle_of_attack)
        """coeff_L, coeff_D, CN_alpha, CT_alpha, CD_90 = self.generate_coeff_from_article(
                        Re, self.angle_of_attack,t, self.cfg.wing_chord
                )"""
        #coeff_L, coeff_D = self.generate_coeff_from_article(self.angle_of_attack)
        self.lift_coeff = coeff_L.clone()
        self.drag_coeff = coeff_D.clone()

        lift_L, drag_D = self.generate_force(apparent_wind2D_b, sail_wing_aire, coeff_L, coeff_D, density_p)

        force = torch.zeros((self.num_envs, 3))


        rot_mat_app_to_boat = self.rotation_matrix(self.apparent_wind_angle)
        #print(f"{rot_mat_app_to_boat.shape, lift_L.unsqueeze(2).shape}")
        self.wind_lift_b[:, :2] = lift_L.clone().detach()
        #torch.bmm(rot_mat_app_to_boat, lift_L.unsqueeze(2)).reshape(self.num_envs, 2)
        self.wind_drag_b[:, :2] = drag_D.clone().detach()

        #torch.bmm(rot_mat_app_to_boat, drag_D.unsqueeze(2)).reshape(self.num_envs, 2)

        """print(f"paral: {check_parallelism(self.wind_lift_b, self.apparent_wind_speed_b)}")
        print(f"perp: {check_perpendicularity(self.wind_drag_b, self.apparent_wind_speed_b)}")"""

        #lift_L*torch.sin(self.apparent_wind_angle) - drag_D*torch.cos(self.apparent_wind_angle)
        force[:, 0] = self.wind_lift_b[:, 0] + self.wind_drag_b[:, 0]
        #lift_L*torch.cos(self.apparent_wind_angle) + drag_D*torch.sin(self.apparent_wind_angle)
        force[:, 1] = self.wind_lift_b[:, 1] + self.wind_drag_b[:, 1]

        return force.clone()

    def generate_true_wind_components(self, Uw: torch.Tensor, beta_w: torch.Tensor, 
                    ship_heading_w:torch.Tensor) -> torch.Tensor:
        """
        This another article implementation

        Generate a true wind vector for each environment.

        Parameters:
        - Uw: Tensor of shape (num_envs,) representing wind speeds.
        - beta_w: Tensor of shape (num_envs,) representing wind directions.

        Returns:
        - True wind vectors as a tensor of shape (num_envs, 2).
        """
        num_envs = Uw.shape[0]
        true_wind = torch.zeros(num_envs, 2, device=Uw.device)
        true_wind[:, 0] = Uw * torch.cos(beta_w - ship_heading_w)
        true_wind[:, 1] = Uw * torch.sin(beta_w - ship_heading_w)

        return true_wind
    
    def generate_apparent_wind_components(self, True_wind2D: torch.Tensor, ship_speed2D: torch.Tensor) -> torch.Tensor:
        """ This another article implementation"""

        app_wind = True_wind2D - ship_speed2D

        return app_wind

    def get_apparent_wind_angle(self, apparent_wind2D_b: torch.Tensor) -> torch.Tensor:
        """
        Calculate the apparent wind angle for each environment.

        Parameters:
        - apparent_wind2D_b: Tensor of shape (num_envs, 2, 1) representing the apparent wind.

        Returns:
        - Apparent wind angles as a tensor of shape (num_envs,).
        """
        return torch.atan2(apparent_wind2D_b[:, 1], apparent_wind2D_b[:, 0])

    def get_angle_of_attack(self, apparent_wind_angle: torch.Tensor, sail_angle: torch.Tensor) -> torch.Tensor:
        """
        Calculate the angle of attack for each environment.

        Parameters:
        - apparent_wind_angle: Tensor of shape (num_envs,) representing apparent wind angles.
        - sail_angle: Tensor of shape (num_envs,) representing sail angles.

        Returns:
        - Angles of attack as a tensor of shape (num_envs,).
        """
        aoa =  sail_angle.reshape(-1,) - apparent_wind_angle.reshape(-1,)
        #(apparent_wind_angle.reshape(-1,) - sail_angle.reshape(-1,) + torch.pi)%(2*torch.pi) - torch.pi
        return torch.atan2(torch.sin(aoa), torch.cos(aoa))

    def generate_force(self, wind_Vapp: torch.Tensor, aire_A: float,coeff_L: torch.Tensor, coeff_D: torch.Tensor,
                       density_p: float = 1.225) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag forces for each environment.

        Parameters:
        - wind_Vapp: Tensor of shape (num_envs,) representing the apparent wind speed.
        - aire_A: Float, representing the sail area.
        - coeff_L: Tensor of shape (num_envs,) representing lift coefficients.
        - coeff_D: Tensor of shape (num_envs,) representing drag coefficients.
        - density_p: Float, air density (default = 1.225 kg/m^3).

        Returns:
        - Tuple of tensors: (lift_L, drag_D), each of shape (num_envs, 2) in the apparent body frame (in which app_wind is expressed).
        """
        wind_Vapp_ampl = torch.sqrt(wind_Vapp[:, 0].square() + wind_Vapp[:, 1].square())

        #print(wind_Vapp.shape, wind_Vapp_ampl.shape)
        wind_V_app_unit = torch.zeros_like(wind_Vapp)
        wind_V_app_unit[:, 0] = wind_Vapp[:, 0]/wind_Vapp_ampl
        wind_V_app_unit[:, 1] = wind_Vapp[:, 1]/wind_Vapp_ampl

        lift_L = 0.5 * density_p * aire_A * coeff_L * torch.square(wind_Vapp_ampl) #(wind_Vapp[:, 0]**2)
        drag_D = 0.5 * density_p * aire_A * coeff_D * torch.square(wind_Vapp_ampl) #(wind_Vapp[:, 1]**2)


        # Cedric's code for boat forces -- Begin -->
        # build sail frame
        sail_angle = self.sail_angle.clone().detach().reshape(-1, ) #self.get_sail_angle(self.apparent_wind_angle, self.angle_of_attack)
        sail_unit_vector = torch.zeros_like(wind_Vapp)

        sail_unit_vector[:, 0] = torch.cos(sail_angle)
        sail_unit_vector[:, 1] = torch.sin(sail_angle)

        sail_ortho_unit_vector = torch.zeros_like(wind_Vapp)
        sail_ortho_unit_vector[:, 0] = - sail_unit_vector[:, 1]
        sail_ortho_unit_vector[:, 1] = sail_unit_vector[:, 0]

        #print(f"{sail_unit_vector.shape} : {wind_V_app_unit.shape}")
        sail_unit_vector = torch.where((torch.sum(sail_unit_vector*wind_V_app_unit, dim=1)<0).unsqueeze(1), 
                                       -sail_unit_vector, sail_unit_vector)
        sail_ortho_unit_vector = torch.where((torch.sum(sail_ortho_unit_vector*wind_V_app_unit, dim=1)<0).unsqueeze(1), 
                                    -sail_ortho_unit_vector, sail_ortho_unit_vector)

        
        aoa_unit_vector = torch.zeros_like(wind_Vapp)

        aoa_unit_vector[:, 0] = torch.cos(self.angle_of_attack)
        aoa_unit_vector[:, 1] = torch.sin(self.angle_of_attack)

        lift_vec = torch.zeros_like(wind_V_app_unit)
        drag_vec = torch.zeros_like(wind_V_app_unit)
        
        lift_vec[:, 0] = lift_L*wind_V_app_unit[:, 1]
        lift_vec[:, 1] = -lift_L*wind_V_app_unit[:, 0]

        lift_vec = torch.where((torch.sum(lift_vec*sail_ortho_unit_vector, dim=1)<0).unsqueeze(1), -lift_vec, lift_vec)

        #print(f"\nperp: {self.check_perpendicularity(lift_vec, wind_Vapp)}")
        
        # parallel to the apparent wind ---> VERIFIED
        drag_vec[:, 0] = drag_D*wind_V_app_unit[:, 0]
        drag_vec[:, 1] = drag_D*wind_V_app_unit[:, 1]
        drag_vec = torch.where((torch.sum(drag_vec*sail_unit_vector, dim=1)<0).unsqueeze(1), -drag_vec, drag_vec)
        
        self.sail_unit_vector = sail_unit_vector.clone()
        self.sail_ortho_unit_vector = sail_ortho_unit_vector.clone()

        #print(f"sail: {torch.sum(sail_unit_vector*wind_V_app_unit, dim=1), torch.sum(sail_ortho_unit_vector*wind_V_app_unit, dim=1)}")
        #print(f"force: {torch.sum(lift_vec*sail_ortho_unit_vector, dim=1), torch.sum(drag_vec*sail_unit_vector, dim=1)}")
        # <-- End 

        """# Lift directions (CCW and CW)
        lift_ccw = lift_L.unsqueeze(1) * torch.stack([wind_V_app_unit[:, 1], -wind_V_app_unit[:, 0]], dim=1)
        lift_cw  = lift_L.unsqueeze(1) * torch.stack([-wind_V_app_unit[:, 1], wind_V_app_unit[:, 0]], dim=1)

        # 5 conditions
        cond1 = (aoa_unit_vector * wind_V_app_unit).sum(dim=1) >= 0
        cond2 = (drag_vec * aoa_unit_vector).sum(dim=1) >= 0
        cond3_ccw = (lift_ccw * torch.stack([aoa_unit_vector[:, 1], -aoa_unit_vector[:, 0]], dim=1)).sum(dim=1) >= 0
        cond3_cw  = (lift_cw  * torch.stack([aoa_unit_vector[:, 1], -aoa_unit_vector[:, 0]], dim=1)).sum(dim=1) >= 0
        cond4_ccw = ((lift_ccw + drag_vec) * wind_V_app_unit).sum(dim=1) >= 0
        cond4_cw  = ((lift_cw + drag_vec) * wind_V_app_unit).sum(dim=1) >= 0
        cond5 = (drag_vec * wind_Vapp).sum(dim=1) >= 0

        # All conditions for CCW and CW
        all_ccw = cond1 & cond2 & cond3_ccw & cond4_ccw & cond5
        all_cw  = cond1 & cond2 & cond3_cw  & cond4_cw  & cond5

        # Default to CCW, switch to CW where CCW conditions are not satisfied and CW are
        lift_vec = torch.where(all_ccw.unsqueeze(1), lift_ccw,
                    torch.where(all_cw.unsqueeze(1), lift_cw, lift_ccw))  # fallback to CCW
        #print(f"paral: {self.check_parallelism(drag_vec, wind_Vapp)}\n")"""

        return lift_vec, drag_vec

    def compute_Reynold(self, speed:torch.Tensor, c:float, density_p:float = 1.225, kv:float=1.42072e-5, 
                        dv:float=1.778e-5):
        """
            Given aerodynamic characteristique, compute the dimensionless number
            Reynolds:
            src http://airfoiltools.com/calculator/reynoldsnumber?MReNumForm%5Bvel%5D=5&MReNumForm%5Bchord%5D=
            0.2&MReNumForm%5Bkvisc%5D=1.4207E-5&yt0=Calculate

            https://www.engineersedge.com/physics/viscosity_of_air_dynamic_and_kinematic_14483.htm

            Params:
            - speed (m/s): speed of low, air in this case
            - c (m): characteristic of the foil, wing chord in this case
            - kv (m/s^2): kinematic viscosity of the flow, air in this case
            - dv (kg.m/s) : dynamic viscosity of the flow, air in this case
            - density_p: density of the flow, air in this case
            Note: constante kv and mu are taken at a temperature of 10 degree

            Return:
            - dimensionless Reynold number
        """

        Re = (speed*c)/kv #(density_p*speed*c)/dv
        return Re

    def generate_coeff_from_article(self, Re:torch.Tensor, alpha:torch.Tensor, t:float, c:float, h = 0):
        """
        Generalized method for computing angle of attack over the full range
        https://www.sciencedirect.com/science/article/pii/S0960148120304833

        - alpha: angle of attack
        - t: thickness: 18% of c for naca0018 -> t=0.036 m for c=0.2m
        - c: chord length
        - h: the distance between the mean camber and the chord line
        - h=0 in our case, since naca0018 has no camber (0 for 1st digit)
        - Re: reynold number
        Note: This method is valid for symmetric airfoil only, check article for asymetric
        """
        # h is the distance between
        CD_90 = 1.98 - 0.64* (0.5*(t/c)**2) - 0.44*t/c - 1.39*h/c
        CN_alpha = CD_90*(torch.sin(alpha) + 0.0023*torch.sin(2*alpha))/    \
        (0.38 + 0.62*torch.abs(torch.sin(alpha)) + 3.7*(t/c)*(torch.cos(alpha)**8))

        CD_f = 0.455/(torch.log10(Re)**2.58)-1700/Re
        CT_alpha = CD_90*0.3*(t/c)*torch.abs(torch.sin(alpha) + 0.1*torch.sin(2*alpha))*    \
        (1-torch.cos(2*alpha)) - CD_f*torch.cos(alpha)

        CL = CN_alpha*torch.cos(alpha) + CT_alpha*torch.sin(alpha)
        CD = CN_alpha*torch.sin(alpha) - CT_alpha*torch.cos(alpha)

        return CL, CD, CN_alpha, CT_alpha, CD_90

    def generate_viterna_coeff(self, alpha:torch.Tensor, AspectR:float, C_stall:float, 
                        CD_stall:float, alpha_stall:float):

        """ This implementation is the Viterna, one of the most popular used for 
            post-stall lift and drag coefficient estimation

            Params: 
            - alpha: angle of attack (90 degree > alpha > alpha_stall and alpha<alpha_min)
            - aspectR: aspect ratio of the airfoil, span/chord
            - 
            Return:
            - CL: lift coefficient
            - CD: drag coefficient 
        """

        CD_max = 1.11 + 0.018*AspectR
        A1 = CD_max/2
        B1 = CD_max
        A2 = (C_stall - CD_max*math.sin(alpha_stall)*math.cos(alpha_stall))*    \
        math.sin(alpha_stall)/(math.cos(alpha_stall)**2)

        B2 = (CD_stall - CD_max*(math.sin(alpha_stall)**2))/math.cos(alpha_stall)
        
        CL = A1*torch.sin(2*alpha) + A2*(torch.cos(alpha)**2)/torch.sin(alpha)
        CD = B1*(torch.sin(alpha)**2) + B2*torch.cos(alpha)

        return CL, CD
    
    def set_coeffs_interpolators(self):

        """
            This function returns the interpolators function for the lift and drag coefficients
            these interpolators were obtained from the Viterna extrapolation methods for the lift and drag coefficients
            Just give a np.ndarray type of angle of attacks in degree and they output the corresponding values of cl and cd
        """
            
        self.xfoil.Re = 200000
        self.xfoil.max_iter = 100
        a, cl, cd, cm, co = self.xfoil.aseq(-20, 20, 1)

        # Assuming a, cl, cd are numpy arrays
        valid_mask = ~np.isnan(a) & ~np.isnan(cl) & ~np.isnan(cd)

        # Filter all arrays accordingly
        a_clean = torch.from_numpy(a[valid_mask])
        cl_clean = torch.from_numpy(cl[valid_mask])
        cd_clean = torch.from_numpy(cd[valid_mask])

        self.max_cl_cd_ratio = torch.max(cl_clean/cd_clean)
        self.max_cl = torch.max(cl_clean)

        idx_stall = torch.argmax(cl_clean)
        idx_min_Cl = torch.argmin(cl_clean)
        idx_min = torch.argmin(cl_clean)

        alpha_stall = a_clean[idx_stall].item()
        alpha_min = a_clean[idx_min].item()
        idx_zero  = (a_clean==0).nonzero().item()
        #print(type(idx_zero), a_clean)
        #print(idx_stall, np.max(cl_clean), cl_clean, a_clean) =======> VALID 
        Cd_stall = cd_clean[idx_stall].item()
        Cl_stall = cl_clean[idx_stall].item()
        Cl_min = cl_clean[idx_min_Cl].item()
        #print(f"cl: {Cl_stall} cl_min: {Cl_min} alpha_stall: {alpha_stall} alpha_min: {alpha_min}")
        alpha_to_90 = torch.linspace(alpha_stall, 90, 50)
        #print(alpha_to_90)
        # Viterna Corigan methods for extrapolation
        alpha_below_min_90 = torch.linspace(-90, alpha_min, 50)

        alpha_n_90_to_180 = torch.linspace(-180, -90, 66)
        alpha_p_90_to_180 = torch.linspace(90, 180, 66)
        
        AR = 5
        CL_to_90, CD_to_90 = self.generate_viterna_coeff((np.pi/180)*alpha_to_90, AR, Cl_stall, Cd_stall, (np.pi/180)*alpha_stall)
        mask = alpha_to_90<20
        CL_to_90[~mask] = 0.1*Cl_stall*torch.rand_like(CL_to_90[~mask])
        #print(CL_to_90)
        CL_below_min_90, CD_below_min_90 = self.generate_viterna_coeff((np.pi/180)*alpha_below_min_90, AR, Cl_min, Cd_stall, (np.pi/180)*alpha_min)
        mask = torch.abs(alpha_below_min_90)<20
        CL_below_min_90[~mask] = 0.1*Cl_stall*torch.rand_like(CL_below_min_90[~mask])
        CL_90_to_0 = torch.concatenate((CL_below_min_90, cl_clean[idx_min:idx_zero]))
        CD_90_to_0 = torch.concatenate((CD_below_min_90, cd_clean[idx_min:idx_zero]))
        #CD_90_to_0[::-1]
        #print(CL_below_min_90, alpha_below_min_90)
        Cl_concatenate = torch.concatenate((-CL_90_to_0, CL_below_min_90, cl_clean[idx_min+1:idx_stall], CL_to_90, CL_90_to_0))
        Cd_concatenate = torch.concatenate((CD_90_to_0.flip(dims=(0, )), CD_below_min_90, cd_clean[idx_min+1:idx_stall], CD_to_90, CD_90_to_0))
        total_alpha = torch.concatenate((alpha_n_90_to_180, alpha_below_min_90, a_clean[idx_min+1:idx_stall], alpha_to_90, alpha_p_90_to_180))


        self.lift_coeff_interpolator = LinearInterpolation(total_alpha, Cl_concatenate, self.device)
        self.drag_coeff_interpolator = LinearInterpolation(total_alpha, Cd_concatenate, self.device)


    
    def generate_coeffs(self, angle_attack_alpha: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag coefficients for each environment.

        Parameters:
        - angle_attack_alpha: Tensor of shape (num_envs,) representing angles of attack in DEGREE.
        - asp_ratio: Aspect ratio of the sail.

        Returns:
        - Tuple of tensors: (coeff_L, coeff_D) each of shape (num_envs,).
        """

        coeff_L = self.lift_coeff_interpolator.compute(angle_attack_alpha)
        coeff_D = self.drag_coeff_interpolator.compute(angle_attack_alpha)


        return coeff_L, coeff_D
    
    def get_sail_angle(self, apparent_wind_angle: torch.Tensor, angle_of_attack: torch.Tensor) -> torch.Tensor:
        """
        Calculate the sail angle for each environment given the angle of attack desired, here 20 degree.

        Parameters:
        - apparent_wind_angle: Tensor of shape (num_envs,) representing apparent wind angles.
        - angle_of_attack: Tensor of shape (num_envs,) representing angles of attack.

        Returns:
        - sail angle as a tensor of shape (num_envs,).
        """
        angle = apparent_wind_angle - angle_of_attack
        angle = torch.atan2(torch.sin(angle), torch.cos(angle))
        #print(f"sail: {angle*(180/torch.pi)} \tapp_ang: {apparent_wind_angle*(180/torch.pi)} \t aoa: {angle_of_attack*(180/torch.pi)}")
        return angle
    
    """def reset_wind_condition(self, env_ids, upwind: torch.Tensor | bool=False, downwind: torch.Tensor | bool=False, 
                             randomize_direction=False, randomize_speed=False):
        randomize wind direction between 0 and 2*pi if params randomize=True 
            upwind: a tensor of boolean or simply a boolean indicating which environments should be upwind
            downwind: a tensor of boolean or simply a boolean indicating which environments should be downwind
        
        if randomize_direction:
            self.Beta_w [env_ids] = torch.pi*torch.zeros_like(self.Beta_w[env_ids]).uniform_(-1, 1)
            
            up_wind_mask = torch.abs(self.Beta_w [env_ids]) > (145/180)*torch.pi
            self.Beta_w [env_ids][~up_wind_mask & upwind] = - torch.pi
            
            down_wind_mask = torch.abs(self.Beta_w [env_ids]) < (35/180)*torch.pi
            self.Beta_w [env_ids][~down_wind_mask & downwind] = 0
                
        if randomize_speed:
            self.Uw[env_ids] = torch.pi*torch.zeros_like(self.Beta_w[env_ids]).uniform_(self.cfg.wind_speed, self.cfg.wind_speed + 3)

        return"""
    
    def reset_wind_condition(self, env_ids, 
                         upwind: torch.Tensor | bool = False,
                         downwind: torch.Tensor | bool = False,
                         beam: torch.Tensor | bool = False,
                         close: torch.Tensor | bool = False,
                         broad: torch.Tensor | bool = False,
                         randomize_direction=False, 
                         randomize_speed=False):
        """
        Randomize wind direction and/or speed for selected environments.
        
        Parameters:
        - env_ids: indices of environments to update
        - upwind: wind from ±180° (against ASV)
        - downwind: wind from 0° (from behind)
        - beam: wind from ±90°
        - close: wind from ±45°
        - broad: wind from ±135°
        - randomize_direction: randomize direction uniformly
        - randomize_speed: randomize speed from cfg.wind_speed to cfg.wind_speed + 3
        """

        num_envs = len(env_ids)

        # Initialize with random direction if requested
        if randomize_direction:
            self.Beta_w[env_ids] = torch.pi * torch.zeros_like(self.Beta_w[env_ids]).uniform_(-1, 1)

        # Define masks
        def to_tensor(val):
            return val if isinstance(val, torch.Tensor) else torch.full((num_envs,), val, dtype=torch.bool, device=self.device)

        upwind_mask = to_tensor(upwind)
        downwind_mask = to_tensor(downwind)
        beam_mask = to_tensor(beam)
        close_mask = to_tensor(close)
        broad_mask = to_tensor(broad)

        # Overwrite direction for each condition
        if upwind_mask.any():
            self.Beta_w[env_ids][upwind_mask] = torch.full_like(self.Beta_w[env_ids][upwind_mask], torch.pi)

        if downwind_mask.any():
            self.Beta_w[env_ids][downwind_mask] = 0.0

        if beam_mask.any():
            self.Beta_w[env_ids][beam_mask] = torch.pi / 2 * torch.randint_like(self.Beta_w[env_ids][beam_mask], low=-1, high=2)

        if close_mask.any():
            self.Beta_w[env_ids][close_mask] = (torch.pi / 4) * torch.randint_like(self.Beta_w[env_ids][close_mask], low=-1, high=2)

        if broad_mask.any():
            self.Beta_w[env_ids][broad_mask] = (3 * torch.pi / 4) * torch.randint_like(self.Beta_w[env_ids][broad_mask], low=-1, high=2)

        # Randomize speed
        if randomize_speed:
            self.Uw[env_ids] = torch.empty_like(self.Uw[env_ids]).uniform_(
                self.cfg.wind_speed, self.cfg.wind_speed + 5)

        return


    def update_wind(self, wind_direction:float | None = None, wind_speed:float | None = None, env_ids: torch.Tensor | None = None):
        """
            This function sets the wind direction and speed for all environments
            Parameters:
                - wind_direction (radians): direction of the wind in the world coordinate frame
                - wind_speed (m/s): speed of the wind in m/s
            Return:
                - None
        """
        
        if env_ids is None:
            indice = torch.arange(self.num_envs, device=self.device)
        else:
            indice = env_ids

        if wind_direction is not None:
            self.Beta_w[indice] = wind_direction 
        if wind_speed is not None:
            self.Uw[indice] = wind_speed

        return
    
    def reset_coefficients(self, env_ids: torch.Tensor | None = None) -> None:
        """
        Resets the drag coefficients for the specified environments.
        Args:
            env_ids (torch.Tensor): Indices of the environments to reset. If None, resets all environments.
        """
        
        return
    
    def rotation_matrix(self, theta: torch.Tensor) -> torch.Tensor:
        """
        Returns the 2D rotation matrix for angle theta (in radians).
        Positive theta = counter-clockwise rotation.
        """
        rot_mat = torch.zeros((self.num_envs, 2, 2), device=self.device)
        rot_mat[:, 0, 0] = torch.cos(theta)
        rot_mat[:, 0, 1] = -torch.sin(theta)
        rot_mat[:, 1, 0] = torch.sin(theta)
        rot_mat[:, 1, 1] = torch.cos(theta)

        return rot_mat

    def check_perpendicularity(self, vec1: torch.Tensor, vec2: torch.Tensor, tol=1e-5) -> torch.Tensor:
        """
        Check if two 2D vectors are perpendicular across all environments.
        Returns a boolean tensor indicating where the dot product is close to zero.
        """
        dot = torch.sum(vec1 * vec2, dim=-1)
        #print(f"dot: {dot}")
        return torch.isclose(dot, torch.zeros_like(dot), atol=tol)

    def check_parallelism(self, vec1: torch.Tensor, vec2: torch.Tensor, tol=1e-5) -> torch.Tensor:
        """
        Check if two 2D vectors are parallel across all environments.
        Returns a boolean tensor indicating where the cross product is close to zero.
        """
        cross = vec1[:, 0] * vec2[:, 1] - vec1[:, 1] * vec2[:, 0]
        #print(f"corss: {cross}")
        return torch.isclose(cross, torch.zeros_like(cross), atol=tol)
    

    def ComputeDampingMatrix(self, vel):
        """
        // From Antonelli 2014: the viscosity of the fluid causes
        // the presence of dissipative drag and lift forces on the
        // body. A common simplification is to consider only linear
        // and quadratic damping terms and group these terms in a
        // matrix Drb
        """
        
        return 

    def ComputeHydrodynamicsEffects(self, quaternions, world_vel):

        return 