# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import torch
from dataclasses import MISSING
import math

from omni.isaac.lab.utils import configclass
from omni.isaac.lab.utils.math import quat_rotate_inverse



@configclass
class AerodynamicsCfg:
    """Configuration for hydrodynamics."""

    wind_direction:float = MISSING # rad/s
    wind_speed:float = MISSING # m/s

    angle_of_attack: float = MISSING # angle of attack of the sail w.r.t wind

    wing_span:float = MISSING # span/length of the sail wing in meter
    wing_chord:float = MISSING # chord/width of the sail wing in meter

    air_density :float = MISSING # air density


class Aerodynamics:
    def __init__(self, num_envs, device, cfg: AerodynamicsCfg):

        self.num_envs = num_envs
        self.device = device
        self.cfg = cfg

        self.angle_of_attack = self.cfg.angle_of_attack*torch.ones(self.num_envs, device=self.device)
        self.apparent_wind_angle = torch.zeros(self.num_envs, device=self.device)
        self.apparent_wind_speed = torch.zeros((self.num_envs, 2), device=self.device)
        self.true_wind_speed2D = torch.zeros((self.num_envs, 2), device=self.device)
        
        self.Uw = self.cfg.wind_speed*torch.ones(self.num_envs, device=self.device) # wind speed of 10 meters per second
        self.Beta_w = self.cfg.wind_direction*torch.ones(self.num_envs, device=self.device) # wind angle of 80 degrees = 80*pi/180 radian
        self.wind_force = torch.zeros((self.num_envs, 3), device=self.device)


        return
    
    def compute_wind_effect(self, Uw:torch.Tensor, Beta_w:torch.Tensor, ship_heading_w:torch.Tensor,
                                 ship_lin_vel2D)->torch.Tensor:
        """ This function will be used to apply wind effect:
                Parameters:
            - Uw: (true) wind speed for all environmenents
            - Beta_w: (true) wind direction for all environmenents
            - ship_heading: heading of the ship in global frame
            - ship_lin_vel2D: 2D coordinates of the linear velocity of the ship in the local (ship) frame
            - AspectR: aspect ratio of the wing -> span/chord  

                Return: 
            - Lift and Drag tensors generated by the wind in all environment
        """
        
        sail_wing_aire = self.cfg.wing_span*self.cfg.wing_chord
        density_p = self.cfg.air_density

        # True wind in sailboat frame
        self.true_wind_speed2D = self.generate_true_wind_components(Uw, Beta_w, ship_heading_w) # ok
        
        apparent_wind2D = self.generate_apparent_wind_components(self.true_wind_speed2D, ship_lin_vel2D)
        
        self.apparent_wind_speed = apparent_wind2D.clone()
        self.apparent_wind_angle = self.get_apparent_wind_angle(apparent_wind2D)
        AspectR = self.cfg.wing_span/self.cfg.wing_chord # Aspect ratio of the rigid wing

        coeff_L, coeff_D = self.generate_coeffs(self.angle_of_attack, AspectR)
        
        lift_L, drag_D = self.generate_force(apparent_wind2D, sail_wing_aire, coeff_L, coeff_D, density_p)
        
        force = torch.zeros((self.num_envs, 3), device=self.device)
        
        force[:, 0] = lift_L*torch.cos(self.apparent_wind_angle) - drag_D*torch.sin(self.apparent_wind_angle)
        force[:, 1] = lift_L*torch.sin(self.apparent_wind_angle) + drag_D*torch.cos(self.apparent_wind_angle)

        return force.clone()

    def generate_true_wind_components(self, Uw: torch.Tensor, beta_w: torch.Tensor, ship_heading_w:torch.Tensor) -> torch.Tensor:
        """
        This another article implementation

        Generate a true wind vector for each environment.

        Parameters:
        - Uw: Tensor of shape (num_envs,) representing wind speeds.
        - beta_w: Tensor of shape (num_envs,) representing wind directions.

        Returns:
        - True wind vectors as a tensor of shape (num_envs, 2).
        """
        num_envs = Uw.shape[0]
        true_wind = torch.zeros(num_envs, 2, device=Uw.device)
        true_wind[:, 0] = Uw * torch.cos(beta_w - ship_heading_w)
        true_wind[:, 1] = Uw * torch.sin(beta_w - ship_heading_w)

        return true_wind
    
    def generate_apparent_wind_components(self, True_wind2D: torch.Tensor, ship_speed2D: torch.Tensor) -> torch.Tensor:
        """ This another article implementation"""

        app_wind = True_wind2D - ship_speed2D

        return app_wind

    def get_apparent_wind_angle(self, apparent_wind2D: torch.Tensor) -> torch.Tensor:
        """
        Calculate the apparent wind angle for each environment.

        Parameters:
        - apparent_wind2D: Tensor of shape (num_envs, 2, 1) representing the apparent wind.

        Returns:
        - Apparent wind angles as a tensor of shape (num_envs,).
        """
        return torch.atan2(apparent_wind2D[:, 1], apparent_wind2D[:, 0])

    def get_angle_of_attack(self, apparent_wind_angle: torch.Tensor, sail_angle: torch.Tensor) -> torch.Tensor:
        """
        Calculate the angle of attack for each environment.

        Parameters:
        - apparent_wind_angle: Tensor of shape (num_envs,) representing apparent wind angles.
        - sail_angle: Tensor of shape (num_envs,) representing sail angles.

        Returns:
        - Angles of attack as a tensor of shape (num_envs,).
        """
        return (apparent_wind_angle - sail_angle + torch.pi)%(2*torch.pi) - torch.pi

    def generate_force(self, wind_Vapp: torch.Tensor, aire_A: float,coeff_L: torch.Tensor, coeff_D: torch.Tensor, density_p: float = 1.225,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag forces for each environment.

        Parameters:
        - wind_Vapp: Tensor of shape (num_envs,) representing the apparent wind speed.
        - aire_A: Float, representing the sail area.
        - coeff_L: Tensor of shape (num_envs,) representing lift coefficients.
        - coeff_D: Tensor of shape (num_envs,) representing drag coefficients.
        - density_p: Float, air density (default = 1.225 kg/m^3).

        Returns:
        - Tuple of tensors: (lift_L, drag_D), each of shape (num_envs,).
        """
        wind_Vapp_ampl = torch.sqrt(wind_Vapp[:, 0].square() + wind_Vapp[:, 1].square())
        
        lift_L = 0.5 * density_p * aire_A * coeff_L * torch.square(wind_Vapp_ampl) #(wind_Vapp[:, 0]**2)
        drag_D = 0.5 * density_p * aire_A * coeff_D * torch.square(wind_Vapp_ampl) #(wind_Vapp[:, 1]**2)

        return lift_L, drag_D 
    
    def generate_coeffs(self, angle_attack_alpha: torch.Tensor, asp_ratio: float) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag coefficients for each environment.

        Parameters:
        - angle_attack_alpha: Tensor of shape (num_envs,) representing angles of attack.
        - asp_ratio: Aspect ratio of the sail.

        Returns:
        - Tuple of tensors: (coeff_L, coeff_D) each of shape (num_envs,).
        """
        coeff_L = (2 * math.pi * angle_attack_alpha) / (1 + (2 / asp_ratio))
        coeff_D = 0.2 * coeff_L  # Taken from "Sail Performance" by Marchaj, page 323

        return coeff_L, coeff_D
    
    def get_sail_angle(self, apparent_wind_angle: torch.Tensor, angle_of_attack: torch.Tensor) -> torch.Tensor:
        """
        Calculate the sail angle for each environment given the angle of attack desired, here 20 degree.

        Parameters:
        - apparent_wind_angle: Tensor of shape (num_envs,) representing apparent wind angles.
        - angle_of_attack: Tensor of shape (num_envs,) representing angles of attack.

        Returns:
        - sail angle as a tensor of shape (num_envs,).
        """
        return apparent_wind_angle - angle_of_attack + torch.pi
    
    def reset_wind_condition(self, randomize=False):
        """ randomize wind direction between 0 and 2*pi if params randomize=True """
        if randomize:
            self.Beta_w = torch.zeros_like(self.Beta_w).uniform_(0, 2*torch.pi)
        return

    def reset_coefficients(self, env_ids: torch.Tensor | None = None) -> None:
        """
        Resets the drag coefficients for the specified environments.
        Args:
            env_ids (torch.Tensor): Indices of the environments to reset. If None, resets all environments.
        """
        
        return
    

    def ComputeDampingMatrix(self, vel):
        """
        // From Antonelli 2014: the viscosity of the fluid causes
        // the presence of dissipative drag and lift forces on the
        // body. A common simplification is to consider only linear
        // and quadratic damping terms and group these terms in a
        // matrix Drb
        """
        
        return 

    def ComputeHydrodynamicsEffects(self, quaternions, world_vel):

        return 
