# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import torch
from dataclasses import MISSING
import math
from dataclasses import field
from omni.isaac.lab.utils import configclass
from omni.isaac.lab.utils.math import quat_rotate_inverse
import matplotlib.pyplot as plt
from xfoil import XFoil
from xfoil.model import Airfoil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import interpolate
from omni.isaac.lab.utils.interpolation import LinearInterpolation

import pandas as pd

# File path to the Naca profile downloaded from xfoil
filepath = "/mnt/gpu_storage/zrr/fsangare/asv-sawasp-fousseyni/Usd/naca0018.csv"
df = pd.read_csv(filepath, skiprows=8, nrows=201)
#print(df.head)

x_coords_naca = 1e-2*df[["X(mm)"]].values
y_coords_naca = 1e-2*df[["Y(mm)"]].values

class FoilDynamicsCfg:
    """Configuration for hydrodynamics."""

    flow_direction:float = MISSING # rad/s
    flow_speed:float = MISSING # m/s
    min_upflow_angle:float = MISSING # m/s # Minimum up flow (when the flow is coming from up, e.g. upflow) tolerable angle
    max_downflow_angle:float = MISSING # m/s # Maximum down flow (when the flow is coming from down, e.g. downflow) tolerable angle

    angle_of_attack: float = MISSING # angle of attack of the foil w.r.t flow

    foil_span:float = MISSING # span/length of the foil foil in meter
    foil_chord:float = MISSING # chord/width of the foil foil in meter

    flow_density :float = MISSING # air density # kg/m^3
    flow_viscosity:float = MISSING # air viscosity # kg/(m.s)

class FoilDynamics:
    def __init__(self, num_envs, device, cfg: FoilDynamicsCfg):
        self.num_envs = num_envs
        self.device = device
        self.cfg = cfg

        self.angle_of_attack = self.cfg.angle_of_attack*torch.ones(self.num_envs, device=self.device)
        self.foil_angle = torch.zeros(self.num_envs, device=self.device)
        self.apparent_flow_angle = torch.zeros(self.num_envs, device=self.device)
        self.apparent_flow_speed_b = torch.zeros((self.num_envs, 2), device=self.device)
        self.true_flow_speed2D_b = torch.zeros((self.num_envs, 2), device=self.device)
        
        self.Uw = self.cfg.flow_speed*torch.ones(self.num_envs, device=self.device) # flow speed of 10 meters per second
        self.Beta_w = self.cfg.flow_direction*torch.ones(self.num_envs, device=self.device) # flow angle of 80 degrees = 80*pi/180 radian
        self.flow_force = torch.zeros((self.num_envs, 3), device=self.device)

        self.lift_coeff = torch.zeros_like(self.Beta_w)
        self.drag_coeff = torch.zeros_like(self.Beta_w)
        
        # lift and drag in the boat frame
        self.flow_lift_b = torch.zeros((self.num_envs, 3), device=self.device) 
        self.flow_drag_b = torch.zeros((self.num_envs, 3), device=self.device)

        self.xfoil = XFoil()
        self.xfoil.print = False
        self.airfoil_set = False
        self.xfoil.airfoil = Airfoil(x_coords_naca, y_coords_naca)  # set later
        
        self.xfoil.n_crit = 9
        self.max_cl_cd_ratio = 0
        self.max_cl = 0
        #self._aerodynamics.xfoil = self.xfoil

        self.foil_unit_vector = torch.zeros_like(self.apparent_flow_speed_b)
        self.foil_ortho_unit_vector = torch.zeros_like(self.apparent_flow_speed_b)

        #self.xfoil = None

        # These coefficients interpolators are initialised in the environement
        self.lift_coeff_interpolator = None
        self.drag_coeff_interpolator = None

        self.max_aero_force = torch.zeros((self.num_envs, 3), device=self.device) # max aerodynamic force in the boat frame

        self.set_coeffs_interpolators()

    
    def compute_flow_effect(self, Uw:torch.Tensor, Beta_w:torch.Tensor, ship_heading_w:torch.Tensor,
                                 ship_lin_vel2D, angle_of_attack:torch.Tensor, foil_angle:torch.Tensor,
                                 update_appw_only=False)->torch.Tensor:
        """ This function will be used to apply flow effect:
                Parameters:
            - Uw: (true) flow speed for all environmenents
            - Beta_w: (true) flow direction for all environmenents
            - ship_heading: heading of the ship in global frame
            - ship_lin_vel2D: 2D coordinates of the linear velocity of the ship in the local (ship) frame
            - AspectR: aspect ratio of the foil -> span/chord

                Return:
            - Lift and Drag tensors generated by the flow in all environment
        """

        foil_aire = self.cfg.foil_span*self.cfg.foil_chord
        density_p = self.cfg.flow_density

        # True flow in foilboat frame
        self.true_flow_speed2D_b = self.generate_true_flow_components(Uw, Beta_w, ship_heading_w) # ok

        apparent_flow2D_b = self.generate_apparent_flow_components(self.true_flow_speed2D_b, ship_lin_vel2D)

        self.apparent_flow_speed_b = apparent_flow2D_b.clone()
        self.apparent_flow_angle = self.get_apparent_flow_angle(apparent_flow2D_b)
        AspectR = self.cfg.foil_span/self.cfg.foil_chord # Aspect ratio of the rigid foil

        Re = self.compute_Reynold(Uw, self.cfg.foil_chord)
        t = 0.18*self.cfg.foil_chord # thickness, naca0018 so 18% of the chord
        coeff_L, coeff_D = self.generate_coeffs((180/torch.pi)*angle_of_attack)
        """coeff_L, coeff_D, CN_alpha, CT_alpha, CD_90 = self.generate_coeff_from_article(
                        Re, self.angle_of_attack,t, self.cfg.foil_chord
                )"""
        #coeff_L, coeff_D = self.generate_coeff_from_article(self.angle_of_attack)
        self.lift_coeff = coeff_L.clone()
        self.drag_coeff = coeff_D.clone()

        lift_L, drag_D = self.generate_force(flow_Vapp=apparent_flow2D_b, angle_of_attack=angle_of_attack, foil_angle=foil_angle, 
                                             aire_A=foil_aire, coeff_L=coeff_L, coeff_D=coeff_D, density_p=density_p)

        force = torch.zeros((self.num_envs, 3))

        #print(f"{rot_mat_app_to_boat.shape, lift_L.unsqueeze(2).shape}")
        self.flow_lift_b[:, :2] = lift_L.clone().detach()
        #torch.bmm(rot_mat_app_to_boat, lift_L.unsqueeze(2)).reshape(self.num_envs, 2)
        self.flow_drag_b[:, :2] = drag_D.clone().detach()

        #torch.bmm(rot_mat_app_to_boat, drag_D.unsqueeze(2)).reshape(self.num_envs, 2)

        """print(f"paral: {check_parallelism(self.flow_lift_b, self.apparent_flow_speed_b)}")
        print(f"perp: {check_perpendicularity(self.flow_drag_b, self.apparent_flow_speed_b)}")"""

        #lift_L*torch.sin(self.apparent_flow_angle) - drag_D*torch.cos(self.apparent_flow_angle)
        force[:, 0] = self.flow_lift_b[:, 0] + self.flow_drag_b[:, 0]
        #lift_L*torch.cos(self.apparent_flow_angle) + drag_D*torch.sin(self.apparent_flow_angle)
        force[:, 1] = self.flow_lift_b[:, 1] + self.flow_drag_b[:, 1]

        return force.clone()
    

    def generate_true_flow_components(self, Uw: torch.Tensor, beta_w: torch.Tensor, 
                    ship_heading_w:torch.Tensor) -> torch.Tensor:
        """
        This another article implementation

        Generate a true flow vector for each environment.

        Parameters:
        - Uw: Tensor of shape (num_envs,) representing flow speeds.
        - beta_w: Tensor of shape (num_envs,) representing flow directions.

        Returns:
        - True flow vectors as a tensor of shape (num_envs, 2).
        """
        num_envs = Uw.shape[0]
        true_flow = torch.zeros(num_envs, 2, device=Uw.device)
        true_flow[:, 0] = Uw * torch.cos(beta_w - ship_heading_w)
        true_flow[:, 1] = Uw * torch.sin(beta_w - ship_heading_w)

        return true_flow
    
    def generate_apparent_flow_components(self, True_flow2D: torch.Tensor, ship_speed2D: torch.Tensor) -> torch.Tensor:
        """ This another article implementation"""

        app_flow = True_flow2D - ship_speed2D

        return app_flow

    def get_apparent_flow_angle(self, apparent_flow2D_b: torch.Tensor) -> torch.Tensor:
        """
        Calculate the apparent flow angle for each environment.

        Parameters:
        - apparent_flow2D_b: Tensor of shape (num_envs, 2, 1) representing the apparent flow.

        Returns:
        - Apparent flow angles as a tensor of shape (num_envs,).
        """
        return torch.atan2(apparent_flow2D_b[:, 1], apparent_flow2D_b[:, 0])

    def get_angle_of_attack(self, apparent_flow_angle: torch.Tensor, foil_angle: torch.Tensor) -> torch.Tensor:
        """
        Calculate the angle of attack for each environment.

        Parameters:
        - apparent_flow_angle: Tensor of shape (num_envs,) representing apparent flow angles.
        - foil_angle: Tensor of shape (num_envs,) representing foil angles.

        Returns:
        - Angles of attack as a tensor of shape (num_envs,).
        """
        
        aoa =  apparent_flow_angle.reshape(-1,) - foil_angle.reshape(-1,) 
        #(apparent_flow_angle.reshape(-1,) - foil_angle.reshape(-1,) + torch.pi)%(2*torch.pi) - torch.pi
        return torch.atan2(torch.sin(aoa), torch.cos(aoa))
    
    def generate_force(self, flow_Vapp: torch.Tensor, angle_of_attack:torch.Tensor, foil_angle:torch.Tensor, aire_A: float,coeff_L: torch.Tensor, coeff_D: torch.Tensor,
                       density_p: float = 1.225) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag forces for each environment.

        Parameters:
        - flow_Vapp: Tensor of shape (num_envs,) representing the apparent flow speed.
        - aire_A: Float, representing the foil area.
        - coeff_L: Tensor of shape (num_envs,) representing lift coefficients.
        - coeff_D: Tensor of shape (num_envs,) representing drag coefficients.
        - density_p: Float, air density (default = 1.225 kg/m^3).

        Returns:
        - Tuple of tensors: (lift_L, drag_D), each of shape (num_envs, 2) in the apparent body frame (in which app_flow is expressed).
        """
        flow_Vapp_ampl = torch.sqrt(flow_Vapp[:, 0].square() + flow_Vapp[:, 1].square())
        flow_Vapp_ampl = torch.clamp(flow_Vapp_ampl, min=1e-6)
        
        #print(flow_Vapp.shape, flow_Vapp_ampl.shape)
        flow_V_app_unit = torch.zeros_like(flow_Vapp)
        flow_V_app_unit[:, 0] = flow_Vapp[:, 0]/flow_Vapp_ampl
        flow_V_app_unit[:, 1] = flow_Vapp[:, 1]/flow_Vapp_ampl

        lift_L = 0.5 * density_p * aire_A * coeff_L * torch.square(flow_Vapp_ampl) #(flow_Vapp[:, 0]**2)
        drag_D = 0.5 * density_p * aire_A * coeff_D * torch.square(flow_Vapp_ampl) #(flow_Vapp[:, 1]**2)


        # Cedric's code for boat forces -- Begin -->
        # build foil frame
        foil_angle = foil_angle.clone().detach().reshape(-1, ) #self.get_foil_angle(self.apparent_flow_angle, self.angle_of_attack)
        foil_unit_vector = torch.zeros_like(flow_Vapp)

        foil_unit_vector[:, 0] = torch.cos(foil_angle)
        foil_unit_vector[:, 1] = torch.sin(foil_angle)

        foil_ortho_unit_vector = torch.zeros_like(flow_Vapp)
        foil_ortho_unit_vector[:, 0] = - foil_unit_vector[:, 1]
        foil_ortho_unit_vector[:, 1] = foil_unit_vector[:, 0]

        #print(f"{foil_unit_vector.shape} : {flow_V_app_unit.shape}")
        foil_unit_vector = torch.where((torch.sum(foil_unit_vector*flow_V_app_unit, dim=1)<0).unsqueeze(1), 
                                       -foil_unit_vector, foil_unit_vector)
        foil_ortho_unit_vector = torch.where((torch.sum(foil_ortho_unit_vector*flow_V_app_unit, dim=1)<0).unsqueeze(1), 
                                    -foil_ortho_unit_vector, foil_ortho_unit_vector)

        
        aoa_unit_vector = torch.zeros_like(flow_Vapp)

        #print(f"aoa: {angle_of_attack.shape}, aoa_unit_vector: {aoa_unit_vector.shape}")
        aoa_unit_vector[:, 0] = torch.cos(angle_of_attack)
        aoa_unit_vector[:, 1] = torch.sin(angle_of_attack)

        lift_vec = torch.zeros_like(flow_V_app_unit)
        drag_vec = torch.zeros_like(flow_V_app_unit)
        
        lift_vec[:, 0] = lift_L*flow_V_app_unit[:, 1]
        lift_vec[:, 1] = -lift_L*flow_V_app_unit[:, 0]

        lift_vec = torch.where((torch.sum(lift_vec*foil_ortho_unit_vector, dim=1)<0).unsqueeze(1), -lift_vec, lift_vec)

        #print(f"\nperp: {self.check_perpendicularity(lift_vec, flow_Vapp)}")
        
        # parallel to the apparent flow ---> VERIFIED
        drag_vec[:, 0] = drag_D*flow_V_app_unit[:, 0]
        drag_vec[:, 1] = drag_D*flow_V_app_unit[:, 1]
        #drag_vec = torch.where((torch.sum(drag_vec*foil_unit_vector, dim=1)<0).unsqueeze(1), -drag_vec, drag_vec)
        
        self.foil_unit_vector = foil_unit_vector.clone()
        self.foil_ortho_unit_vector = foil_ortho_unit_vector.clone()

        #print(f"foil: {torch.sum(foil_unit_vector*flow_V_app_unit, dim=1), torch.sum(foil_ortho_unit_vector*flow_V_app_unit, dim=1)}")
        #print(f"force: {torch.sum(lift_vec*foil_ortho_unit_vector, dim=1), torch.sum(drag_vec*foil_unit_vector, dim=1)}")
        # <-- End 

        return lift_vec, drag_vec

    def compute_Reynold(self, speed:torch.Tensor, c:float, density_p:float = 1.225, kv:float=1.42072e-5, 
                        dv:float=1.778e-5):
        """
            Given aerodynamic characteristique, compute the dimensionless number
            Reynolds:
            src http://airfoiltools.com/calculator/reynoldsnumber?MReNumForm%5Bvel%5D=5&MReNumForm%5Bchord%5D=
            0.2&MReNumForm%5Bkvisc%5D=1.4207E-5&yt0=Calculate

            https://www.engineersedge.com/physics/viscosity_of_air_dynamic_and_kinematic_14483.htm

            Params:
            - speed (m/s): speed of flow
            - c (m): characteristic of the foil, foil chord in this case
            - kv (m/s^2): kinematic viscosity of the flow
            - dv (kg.m/s) : dynamic viscosity of the flow
            - density_p: density of the flow
            Note: constante kv and mu are taken at a temperature of 10 degree

            Return:
            - dimensionless Reynold number
        """

        Re = (speed*c)/kv #(density_p*speed*c)/dv
        return Re
    
    def generate_viterna_coeff(self, alpha:torch.Tensor, AspectR:float, C_stall:float, 
                        CD_stall:float, alpha_stall:float):

        """ This implementation is the Viterna, one of the most popular used for 
            post-stall lift and drag coefficient estimation

            Params: 
            - alpha: angle of attack (90 degree > alpha > alpha_stall and alpha<alpha_min)
            - aspectR: aspect ratio of the airfoil, span/chord
            - 
            Return:
            - CL: lift coefficient
            - CD: drag coefficient 
        """

        CD_max = 1.11 + 0.018*AspectR
        A1 = CD_max/2
        B1 = CD_max
        A2 = (C_stall - CD_max*math.sin(alpha_stall)*math.cos(alpha_stall))*    \
        math.sin(alpha_stall)/(math.cos(alpha_stall)**2)

        B2 = (CD_stall - CD_max*(math.sin(alpha_stall)**2))/math.cos(alpha_stall)
        
        CL = A1*torch.sin(2*alpha) + A2*(torch.cos(alpha)**2)/torch.sin(alpha)
        CD = B1*(torch.sin(alpha)**2) + B2*torch.cos(alpha)

        return CL, CD
    
    def set_coeffs_interpolators(self):

        """
            This function returns the interpolators function for the lift and drag coefficients
            these interpolators were obtained from the Viterna extrapolation methods for the lift and drag coefficients
            Just give a np.ndarray type of angle of attacks in degree and they output the corresponding values of cl and cd
        """
            
        self.xfoil.Re = 200000
        self.xfoil.max_iter = 100
        a, cl, cd, cm, co = self.xfoil.aseq(-20, 20, 1)

        # Assuming a, cl, cd are numpy arrays
        valid_mask = ~np.isnan(a) & ~np.isnan(cl) & ~np.isnan(cd)

        # Filter all arrays accordingly
        a_clean = torch.from_numpy(a[valid_mask])
        cl_clean = torch.from_numpy(cl[valid_mask])
        cd_clean = torch.from_numpy(cd[valid_mask])

        self.max_cl_cd_ratio = torch.max(cl_clean/cd_clean)
        self.max_cl = torch.max(cl_clean)

        idx_stall = torch.argmax(cl_clean)
        idx_min_Cl = torch.argmin(cl_clean)
        idx_min = torch.argmin(cl_clean)

        alpha_stall = a_clean[idx_stall].item()
        alpha_min = a_clean[idx_min].item()
        idx_zero  = (a_clean==0).nonzero().item()
        #print(type(idx_zero), a_clean)
        #print(idx_stall, np.max(cl_clean), cl_clean, a_clean) =======> VALID 
        Cd_stall = cd_clean[idx_stall].item()
        Cl_stall = cl_clean[idx_stall].item()
        Cl_min = cl_clean[idx_min_Cl].item()
        #print(f"cl: {Cl_stall} cl_min: {Cl_min} alpha_stall: {alpha_stall} alpha_min: {alpha_min}")
        alpha_to_90 = torch.linspace(alpha_stall, 90, 50)
        #print(alpha_to_90)
        # Viterna Corigan methods for extrapolation
        alpha_below_min_90 = torch.linspace(-90, alpha_min, 50)

        alpha_n_90_to_180 = torch.linspace(-180, -90, 66)
        alpha_p_90_to_180 = torch.linspace(90, 180, 66)
        
        AR = 5
        CL_to_90, CD_to_90 = self.generate_viterna_coeff((np.pi/180)*alpha_to_90, AR, Cl_stall, Cd_stall, (np.pi/180)*alpha_stall)
        mask = alpha_to_90<20
        #CL_to_90[~mask] = 0.1*Cl_stall*torch.rand_like(CL_to_90[~mask])
        #print(CL_to_90)
        CL_below_min_90, CD_below_min_90 = self.generate_viterna_coeff((np.pi/180)*alpha_below_min_90, AR, Cl_min, Cd_stall, (np.pi/180)*alpha_min)
        mask = torch.abs(alpha_below_min_90)<20
        #CL_below_min_90[~mask] = 0.1*Cl_stall*torch.rand_like(CL_below_min_90[~mask])
        CL_90_to_0 = torch.concatenate((CL_below_min_90, cl_clean[idx_min:idx_zero]))
        CD_90_to_0 = torch.concatenate((CD_below_min_90, cd_clean[idx_min:idx_zero]))
        #CD_90_to_0[::-1]
        #print(CL_below_min_90, alpha_below_min_90)
        Cl_concatenate = torch.concatenate((-CL_90_to_0, CL_below_min_90, cl_clean[idx_min+1:idx_stall], CL_to_90, CL_90_to_0))
        Cd_concatenate = torch.concatenate((CD_90_to_0.flip(dims=(0, )), CD_below_min_90, cd_clean[idx_min+1:idx_stall], CD_to_90, CD_90_to_0))
        total_alpha = torch.concatenate((alpha_n_90_to_180, alpha_below_min_90, a_clean[idx_min+1:idx_stall], alpha_to_90, alpha_p_90_to_180))


        self.lift_coeff_interpolator = LinearInterpolation(total_alpha, Cl_concatenate, self.device)
        self.drag_coeff_interpolator = LinearInterpolation(total_alpha, Cd_concatenate, self.device)

    
    def generate_coeffs(self, angle_attack_alpha: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """
        Generate lift and drag coefficients for each environment.

        Parameters:
        - angle_attack_alpha: Tensor of shape (num_envs,) representing angles of attack in DEGREE.
        - asp_ratio: Aspect ratio of the foil.

        Returns:
        - Tuple of tensors: (coeff_L, coeff_D) each of shape (num_envs,).
        """

        coeff_L = self.lift_coeff_interpolator.compute(angle_attack_alpha)
        coeff_D = self.drag_coeff_interpolator.compute(angle_attack_alpha)


        return coeff_L, coeff_D
    
    def get_foil_angle(self, apparent_flow_angle: torch.Tensor, angle_of_attack: torch.Tensor) -> torch.Tensor:
        """
        Calculate the foil angle for each environment given the angle of attack desired, here 20 degree.

        Parameters:
        - apparent_flow_angle: Tensor of shape (num_envs,) representing apparent flow angles.
        - angle_of_attack: Tensor of shape (num_envs,) representing angles of attack.

        Returns:
        - foil angle as a tensor of shape (num_envs,).
        """
        angle = apparent_flow_angle - angle_of_attack 
        angle = torch.atan2(torch.sin(angle), torch.cos(angle))
        #print(f"foil: {angle*(180/torch.pi)} \tapp_ang: {apparent_flow_angle*(180/torch.pi)} \t aoa: {angle_of_attack*(180/torch.pi)}")
        return angle
    
    def get_max_aero_force(self, true_wind, max_boat_speed=1.5) -> torch.Tensor:
        """
        Returns the maximum aerodynamic force (lift) in the boat frame,
        assuming apparent wind angle of 90° (max lift), i.e. 
        V_app = sqrt(true_wind^2 + max_boat_speed^2).
        
        Parameters:
            true_wind: Tensor of shape (num_envs,) | float with wind speeds.
            max_boat_speed: float, maximum boat speed magnitude (m/s).

        Returns:
            max_aero_force: Tensor of shape (num_envs, 3) with lift force in boat frame.
        """
        if isinstance(true_wind, float):
            true_wind = torch.tensor([true_wind], device=self.device)
        V_app = torch.sqrt(true_wind ** 2 + max_boat_speed ** 2)
        sail_wing_area = self.cfg.foil_span * self.cfg.foil_chord
        density = self.cfg.flow_density
        max_cl = self.max_cl

        lift_magnitude = 0.5 * density * sail_wing_area * max_cl * V_app ** 2

        return lift_magnitude
    
    def reset_flow_condition(
        self,
        env_ids=None,
        upflow=False,
        downflow=False,
        beam=False,
        close=False,
        broad=False,
        randomize_direction=False,
        randomize_speed=False,
        fixed=False
    ):
        if env_ids is None:
            env_ids = torch.arange(self.num_envs, device=self.device)
        num_envs = len(env_ids)

        # Optionally randomize speed
        if randomize_speed:
            self.Uw[env_ids] = torch.empty(num_envs, device=self.device).uniform_(
                self.cfg.flow_speed, self.cfg.flow_speed + 5
            )

        # Define available categories
        choices = []

        if randomize_direction:
            choices.append("random")
        if upflow:
            choices.append("upflow")
        if downflow:
            choices.append("downflow")
        if beam:
            choices.append("beam")
        if close:
            choices.append("close")
        if broad:
            choices.append("broad")
        if not choices:
            choices.append("no_flow")

        indices = torch.randint(len(choices), (num_envs,), device=self.device)
        beta = torch.empty(num_envs, device=self.device)

        for i, name in enumerate(choices):
            mask = (indices == i)
            if not mask.any():
                continue

            n = mask.sum()

            if name == "random":
                beta[mask] = torch.pi * torch.empty(n, device=self.device).uniform_(-1, 1)

            elif name == "upflow":
                # Upflow: angles between 135-180 and -180 to -135 degrees
                beta_upflow = torch.empty(n, device=self.device).uniform_(136, 180)
                # Randomly assign negative signs to half the samples
                if fixed:
                    beta_upflow = 180
                sign = torch.randint(0, 2, (n,), device=self.device) * 2 - 1  # -1 or 1
                beta[mask] = torch.deg2rad(sign * beta_upflow)

            elif name == "downflow":
                # ±30° (flow from behind)
                # Downflow: angles between -30 and 30 degrees
                beta[mask] = torch.deg2rad(torch.empty(n, device=self.device).uniform_(-45, 45))
                if fixed:
                    beta[mask] = 0

            elif name == "beam":
                # ±90° (flow from sides)
                beta_beam = torch.empty(n, device=self.device).uniform_(90, 90)
                if fixed:
                    beta_beam = 90
                # Randomly assign negative signs to half the samples
                sign = torch.randint(0, 2, (n,), device=self.device) * 2 - 1  # -1 or 1
                beta[mask] = torch.deg2rad(sign * beta_beam)
                
            elif name == "close":
                # ±45° (close haul)
                beta_close = torch.empty(n, device=self.device).uniform_(91, 135)
                if fixed:
                    beta_close = 115
                # Randomly assign negative signs to half the samples
                sign = torch.randint(0, 2, (n,), device=self.device) * 2 - 1  # -1 or 1
                beta[mask] = torch.deg2rad(sign * beta_close)

            elif name == "broad":
                # ±135° (broad reach)
                beta_broad = torch.empty(n, device=self.device).uniform_(46, 90)
                if fixed:
                    beta_broad = 70
                sign = torch.randint(0, 2, (n,), device=self.device) * 2 - 1  # -1 or 1
                beta[mask] = torch.deg2rad(sign * beta_broad)

            elif name == "no_flow":
                beta[mask] = 0.0
                self.Uw[env_ids][mask] = 0.0

        self.Beta_w[env_ids] = beta

    def update_flow(self, flow_direction:float | None = None, flow_speed:float | None = None, env_ids: torch.Tensor | None = None):
        """
            This function sets the flow direction and speed for all environments
            Parameters:
                - flow_direction (radians): direction of the flow in the world coordinate frame
                - flow_speed (m/s): speed of the flow in m/s
            Return:
                - None
        """
        
        if env_ids is None:
            indice = torch.arange(self.num_envs, device=self.device)
        else:
            indice = env_ids

        if flow_direction is not None:
            self.Beta_w[indice] = flow_direction 
        if flow_speed is not None:
            self.Uw[indice] = flow_speed

        return 

